// lib/export/classroom-zip-types.ts
//
// ZIP archive format for classroom export/import (Phase 6 / upstream #17,
// adapted for server-side OpenMAIC-RU storage).
//
// Layout of the .maic.zip archive:
//
//   meta.json              — top-level integrity + provenance info
//   classroom.json         — full PersistedClassroomData (stage + scenes + manifest history)
//   media/<elementId>/<vNNN>.<ext>          — versioned image/video files referenced by manifest.assets
//   audio/<actionId>/<vNNN>.<ext>           — versioned TTS audio files referenced by speech actions
//   interactive/<sceneId>/<vNNN>.html       — versioned interactive slide HTML referenced by manifest.interactiveSlides
//
// All files in media/, audio/, interactive/ are addressed by RELATIVE paths
// from the classroom directory — exactly as they exist on disk under
// `data/classrooms/<id>/...`. The import flow re-creates them as-is at the
// new (suffixed) classroom id.
//
// The `meta.json` carries:
//   - formatVersion           — incremented on breaking layout changes
//   - exportedAt              — ISO timestamp
//   - appVersion              — OpenMAIC-RU package.json version (incl. RU fork suffix if any)
//   - sourceClassroomId       — original id at export time (may be reused on import for prefix)
//   - integrity               — sha256 of canonicalised classroom.json + sorted file list
//   - fileCount, totalBytes   — sanity numbers for UI / diagnostics
//
// The export is a **server-side** operation. We do NOT ship the upstream
// browser-side IndexedDB exporter (incompatible with our filesystem layout
// and managed-mode security model).
import type { ClassroomManifest } from '@/lib/types/manifest';
import type { Stage, Scene } from '@/lib/types/stage';

export const CLASSROOM_ZIP_FORMAT_VERSION = 1 as const;
export const CLASSROOM_ZIP_EXTENSION = '.maic.zip';
export const CLASSROOM_ZIP_MIME_TYPE = 'application/zip';

/** File path inside the ZIP for the embedded classroom JSON. */
export const ZIP_ENTRY_CLASSROOM_JSON = 'classroom.json';
/** File path inside the ZIP for export metadata. */
export const ZIP_ENTRY_META_JSON = 'meta.json';

/**
 * Top-level metadata stored as `meta.json` in the ZIP root.
 * Keep ALL fields backwards-compatible — readers must tolerate older versions.
 */
export interface ClassroomZipMeta {
  formatVersion: typeof CLASSROOM_ZIP_FORMAT_VERSION;
  exportedAt: string;
  appVersion: string;
  /** Original classroom id at export time. Useful for traceability + slug prefix on import. */
  sourceClassroomId: string;
  /** sha256 over `classroom.json` bytes + sorted list of media-file paths+sizes. */
  integrity: {
    algo: 'sha256';
    /** Hash of the canonical classroom.json contents (UTF-8 bytes). */
    classroomJsonSha256: string;
    /** Hash of `<path>\n<sha256>\n` lines, one per non-classroom-json entry, sorted. */
    mediaIndexSha256: string;
  };
  /** Number of files inside `media/`, `audio/`, `interactive/`. */
  fileCount: number;
  /** Sum of uncompressed byte sizes of media files (excludes classroom.json + meta.json). */
  totalBytes: number;
  /**
   * RU fork marker — distinguishes archives generated by the RU fork from
   * upstream-only archives that may follow a different schema.
   */
  fork?: 'osvaivai-ru';
}

/**
 * The structure embedded as `classroom.json` inside the ZIP.
 *
 * This is intentionally identical to `PersistedClassroomData` so that the
 * import handler can hand it directly to `persistClassroom` after path
 * rewriting. Includes the full manifest with version history (NOT just the
 * latest version) so partial-regen chains and asset/interactive history are
 * preserved on round-trip.
 */
export interface ClassroomZipClassroomDoc {
  id: string;
  stage: Stage;
  scenes: Scene[];
  createdAt: string;
  manifest?: ClassroomManifest;
}
